mainprefix: "-"
defaultjoinmessage: "{user} Joined Invited By {Inviter} (Inviter Invites: {inv})"
defaultleavemessage: "{user} Left, Invited by {inviter}"
token: "NzwOTc3MDk3MTg2OTM0ODI0.X5laYA.3v3K4vOGnZ5I9SEqQoIjZAT3"
color: "GREEN"
